# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab821ed4b5f03caa1a0b39f06375b2a00ccec1f5f8cc5ad7e9eb4db400a6faac032475286c3814e0d3c21437cd5fd9b119029196fa5cc6ddc7d09b30ac73d5c0

test:
  secret_key_base: 4c26d67c161e01c06dbfd857926f9e64495fcb1b6a66ca6b44086c2554d68fde911e3d71dc1f917008429f9ba7c441d14f436d0483544fec4197906a664c5671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
